name: Get New Package Version
description: Sets the version as ENV variable.

inputs:
  CHANNEL:
    required: true
    description: 'The channel to get the version to (ga, cloud, beta).'
  POSTFIX:
    required: false
    description: 'The postfix that will be added to the package version -rc / -test / "" (empty string).'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
            CLEAN_PACKAGE_VERSION=$(node -p "require('./package.json').version")

            PACKAGE_VERSION=${CLEAN_PACKAGE_VERSION}-${{ inputs.CHANNEL }}${{ inputs.POSTFIX }}

            echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
            echo "CLEAN_PACKAGE_VERSION=${CLEAN_PACKAGE_VERSION}" >> $GITHUB_ENV
